name: Java

on:
  push:
  workflow_dispatch:

jobs:
  code_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info

  build_image:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()
    needs: code_check
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to docker hub
        run: sudo docker login -u danielmaria -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: sudo docker build -t danielmaria/lanchonetebairro-app:latest .

      - name: Publish image to DockerHub
        run: sudo docker push danielmaria/lanchonetebairro-app:latest



  deploy_ec2:
    runs-on: [self-hosted]
    if: github.ref == 'refs/heads/main' && success()
    needs: build_image
    steps:
      -  name: Checkout
         uses: actions/checkout@v2

      - name: Pull Image from docker hub
        run: sudo docker pull danielmaria/lanchonetebairro-app:latest

      - name: Delete old container
        run: sudo docker rm -f lanchonetebairro-app-container || true

      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 -e MYSQL_URL=${{secrets.MYSQL_URL}} -e MYSQL_ROOT_PASSWORD=${{secrets.MYSQL_ROOT_PASSWORD}} -e MYSQL_ROOT_USERNAME=${{secrets.MYSQL_ROOT_USERNAME}} --name lanchonetebairro-app-container danielmaria/lanchonetebairro-app:latest
